### ISSUE TITLE
Logo image link is broken on README

### ISSUE THREAD

**Issue by peter279k** [hellofresh/stats-php#16]
As title, it seems that the `https://www.hellofresh.de/images/hellofresh/press/HelloFresh_Logo.png` link is broken.

Maybe this logo link should change into `https://img.hellofresh.com/image/upload/c_scale,f_auto,q_100,w_200/Hello_Fresh_Lockup.png`.

**Comment by vgarvardt** [comment]
Thank you for reporting Will fix it shortly.

**Comment by vgarvardt** [comment]
I removed logo completely - we do not really need it here.
